name: "firebase-tools"
author: "Gustavo Hoirisch"
description: "Wraps the firebase-tools CLI to enable common commands or to be used in a script."
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  args:
    description: 'The arguments to pass to the firebase-tools CLI'
    required: true
  PROJECT_PATH:
    description: 'The path to the project directory'
    required: false
  PROJECT_ID:
    description: 'The Firebase project ID to use'
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.args }}
      shell: bash
      env:
        PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
        PROJECT_ID: ${{ inputs.PROJECT_ID }}
