name: "firebase-tools"
author: "Gustavo Hoirisch"
description: "Wraps the firebase-tools CLI to enable common commands or to be used in a script."
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  args:
    description: 'The arguments to pass to the firebase-tools CLI'
    required: true
  firebase_token:
    description: 'The Firebase token to use for authentication'
    required: false
  gcp_sa_key:
    description: 'The GCP service account key to use for authentication'
    required: false
  project_path:
    description: 'The path to the project directory'
    required: false
  project_id:
    description: 'The Firebase project ID to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.args }}
      shell: bash
